Update index.js
A resolution for the following:

Error: Cannot find module '../node_modules/msl-server/web-server'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)